# Generated by Django 2.1.7 on 2019-05-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_url', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('prob_lluvia', models.IntegerField()),
                ('altitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400)),
                ('num_comentarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('titulo_pagina', models.CharField(default='Página usuario', max_length=100)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('color_fondo', models.CharField(max_length=50)),
                ('pueblos', models.ManyToManyField(to='MiTiempo.Pueblo')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='pueblo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiTiempo.Pueblo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiTiempo.Usuario'),
        ),
    ]
