# Generated by Django 2.1.7 on 2019-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0002_auto_20190519_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cookie',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
