# Generated by Django 2.1.7 on 2019-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0005_auto_20190520_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='color_fondo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='size',
            field=models.IntegerField(default=15),
        ),
    ]
