# Generated by Django 2.1.7 on 2019-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0006_auto_20190521_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='color',
            field=models.CharField(default='#1d7ffd', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='color_fondo',
            field=models.CharField(default='lightblue', max_length=50),
        ),
    ]
