# Generated by Django 2.1.7 on 2019-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0007_auto_20190521_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pueblo',
            name='p_id',
            field=models.CharField(default='id', max_length=10),
        ),
    ]
