# Generated by Django 2.1.7 on 2019-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0008_pueblo_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pueblo',
            name='p_id',
            field=models.CharField(max_length=10),
        ),
    ]
